export const TEMPLATE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_REVIEW: 'IN_REVIEW',
  PAUSED: 'PAUSED',
  DISABLED: 'DISABLED',
  PENDING_DELETION: 'PENDING_DELETION',
  DELETED: 'DELETED',
  LIMIT_REACHED: 'LIMIT_REACHED',
  APPEAL_REQUESTED: 'APPEAL_REQUESTED',
  DRAFT: 'DRAFT',
} as const;
