export enum OnboardingState {
  INIT = 'INIT',
  ATTACHED = 'ATTACHED',
  OTP_SENT = 'OTP_SENT',
  VERIFIED = 'VERIFIED',
  REGISTERED_PENDING = 'REGISTERED_PENDING',
  LIVE = 'LIVE',
  FAILED_TEMP = 'FAILED_TEMP',
  FAILED_PERMANENT = 'FAILED_PERMANENT',
}
