export enum OnboardingEvents {
  STARTED = 'ONBOARDING_STARTED',
  ATTACHED = 'ONBOARDING_ATTACHED',
  OTP_SENT = 'OTP_SENT',
  VERIFIED = 'VERIFIED',
  REGISTERED_PENDING = 'REGISTERED_PENDING',
  LIVE = 'ONBOARDING_LIVE',
  FAILED = 'ONBOARDING_FAILED',
}
